# Generated by Django 4.1.4 on 2023-02-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetomadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestorder',
            name='classroom',
            field=models.CharField(default='default title', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestorder',
            name='status',
            field=models.CharField(default='def title', max_length=20),
            preserve_default=False,
        ),
    ]
