# Generated by Django 4.1.4 on 2023-02-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetomadmin', '0003_requestorder_date_order_alter_requestorder_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestorder',
            name='computer',
            field=models.CharField(default='def', max_length=30),
            preserve_default=False,
        ),
    ]
