# Generated by Django 4.1.4 on 2023-02-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetomadmin', '0005_requestorder_family_user_tg_requestorder_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestorder',
            name='date_finish',
            field=models.CharField(default='22', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestorder',
            name='time_finish',
            field=models.CharField(default='22', max_length=30),
            preserve_default=False,
        ),
    ]
